make kreversi and knetwalk global highscore aware
svn path=/branches/KDE/3.5/kdegames/knetwalk/; revision=529243

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -19,3 +19,51 @@ appdata_DATA = eventsrc
 messages: rc.cpp
 	$(XGETTEXT) rc.cpp *.cpp -o $(podir)/knetwalk.pot
 
+# for system-wide highscore file
+DESTBIN = $(DESTDIR)$(bindir)/$(bin_PROGRAMS)
+DESTHIGHSCORES = $(DESTDIR)$(HIGHSCORE_DIRECTORY)
+DESTSCORES = $(DESTDIR)$(HIGHSCORE_DIRECTORY)/$(bin_PROGRAMS).scores
+
+install-data-local:
+	@if test x$(HIGHSCORE_DIRECTORY) != x; then \
+	  echo "********************************************************" ;\
+	  echo "" ;\
+	  echo "This game is installed sgid \"games\" to use the" ;\
+	  echo "system-wide highscore file (in "$(HIGHSCORE_DIRECTORY)")." ;\
+	  echo "" ;\
+	  echo "If the system-wide highscore file does not exist, it is" ;\
+          echo "created with the correct ownership and permissions. See the" ;\
+          echo "INSTALL file in \"kdegames/libkdegames/highscore\" for details." ;\
+	  echo "" ;\
+	  echo "********************************************************" ;\
+	fi 
+
+install-exec-hook:
+	@if test x$(HIGHSCORE_DIRECTORY) != x; then \
+	  chown $(highscore_user):$(highscore_group) $(DESTBIN) \
+	  || echo "Error: Could not install the game with correct permissions !!" ;\
+	fi
+
+	@if test x$(HIGHSCORE_DIRECTORY) != x; then \
+		mkdir -p $(DESTHIGHSCORES) && \
+		chown $(highscore_user):$(highscore_group) $(DESTHIGHSCORES) \
+		&& chmod 750 $(DESTHIGHSCORES) \
+	        || echo "Error: Could not create the highscore directory with correct permissions !!" ;\
+	fi
+
+	@if test x$(HIGHSCORE_DIRECTORY) != x; then \
+	   chown $(highscore_user):$(highscore_group) $(DESTBIN) \
+	   || echo "Error: Could not install the game with correct permissions !!" ;\
+	fi
+
+	@if test ${setgid} = true; then \
+	   chmod 2755  $(DESTBIN) \
+	   || echo "Error: Could not install the game with correct permissions !!" ;\
+	fi
+
+	@if test x$(HIGHSCORE_DIRECTORY) != x; then \
+	   touch $(DESTSCORES) && chown $(highscore_user):$(highscore_group) $(DESTSCORES) \
+	   && chmod 0660 $(DESTSCORES) \
+	   || echo "Error: Could not create system-wide highscore file with correct permissions !!" ;\
+	fi
+
